directory: ~/Desktop/NewMusic
library: ~/Desktop/NewMusicDB/newlibrary.blb

import: 
    copy: yes
    move: yes
    log: beetslog.txt

plugins: graduatorPlug 
pluginpath: ~/Desktop/PLUGIN/beetsplug

graduatorPlug:
    auto: True
    minwidth: 0
    maxwidth: 0
    quality: 0
    cautious: False
    cover_names: ['cover', 'front', 'art', 'album', 'folder']
    sources: ['coverart', 'google', 'wikipedia']
    google_key: None
    google_engine: u'001442825323518660753:hrh5ch1gjzm'
    store_source: False
    high_resolution: False


replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': ''
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
