directory: ~/Desktop/NewMusic
library: ~/Desktop/NewMusicDB/newlibrary.blb

import: 
    copy: yes
    move: yes
    log: beetslog.txt

plugins: graduatorPlug 
pluginpath: ~/Desktop/PLUGIN/beetsplug

graduatorPlug:
    auto: True
    minwidth: 0
    maxwidth: 2000
    quality: 0
    cautious: False
    cover_names: ['cover', 'front', 'art', 'album', 'folder']
    sources: ['coverart', 'google', 'wikipedia']
    google_key: u'AIzaSyBb51-r1BX5jAseSO1RbN7Zi_tObJp8Rgc'
    google_engine: u'003601479673604743105:qwuwbgnmqss'
    store_source: False
    high_resolution: False

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': ''
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
