directory: ~/Desktop/NewMusic
library: ~/Desktop/NewMusicDB/newlibrary.db

import: 
    copy: yes
    move: yes
    log: beetslog.txt

plugins: graduatorPlug 
pluginpath: ~/Desktop/PLUGIN/beetsplug

graduatorPlug:
    auto: True
    force: False
    minwidth: 0
    maxwidth: 2000
    quality: 0
    cautious: False
    cover_names: ['cover']
    source: ['coverart']
    lyric: ['genius']
    default_lyrics: None
    force: False
    local: False
    store_source: False
    high_resolution: False
    genius_api_key: ix67dChoM3LyJQKeqhnG2_Z6hRUl_KuAoIJH4RxVvbfmC2r9NSlriHCjDbz7PAu8
   
                     

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': ''
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
