directory: ~/Desktop/NewMusic
library: ~/Desktop/NewMusicDB/newlibrary.db

import: 
    copy: yes
    move: yes
    log: beetslog.txt

plugins: graduatorPlug 
pluginpath: ~/Desktop/PLUGIN/beetsplug

graduatorPlug:
    auto: True
    force: False
    maxwidth: 2000
    cover_names: ['cover']
    source: ['coverart']
    lyric: ['genius']
    force: False
    local: False
    store_source: False
    high_resolution: False
    genius_api_key: ####genius api key should not be shared
   
                     

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': ''
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _
